MusicApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness:true

end

MusicApp/app/models/user.rb
class User < ApplicationRecord
    before_validation :ensure_session_token
    attr_reader :password
    validates :email, presence: true, uniqueness: true
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 8, allow_nil: true}

    #SPIRE
    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        if user && user.is_password?(password)
            return user
        else
            return nil 
        end

    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
       b_crypt = BCrypt::Password.new(self.password_digest)
       b_crypt.is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    private
    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end

    def generate_unique_session_token
        token = SecureRandom::urlsafe_base64
        while User.exists?(session_token: token)
            token = SecureRandom::urlsafe_base64
        end
        token
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #CRRLLL
    skip_before_action :verify_authenticity_token
    helper_method :logged_in?, :current_user

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end


    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil 
        @current_user = nil
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: [:show, :edit, :update, :destroy]

    def set_band
        @band = Band.find_by(id: params[:id])
    end

    def show
        set_band
        @band = Band.find_by(id: params[:id])
        render :show
    end

    def new
        @band = Band.new
    end

    def index
        @bands = Band.all
        render :index
    end

    def create 
        @band = Band.new(band_params)
        if @band.save
            render json: 'saved!'
        else
            render json: 'whoops!'
        end
    end

    def edit
        render :edit
    end

    def update
        set_band

        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            render :edit
        end
    end

    def destroy
        band = Band.find_by(id: params[:id])
        band.destroy
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end
    
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        @user = User.new
        render :new
    end

    def create
        email = params[:user][:email]
        password = params[:user][:password]

        @user = User.find_by_credentials(email, password)

        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    def destroy
        logout
        redirect_to new_session_url
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        user = User.find_by(id: params[:id])
        render :show
    end

    def new
        user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save!
            login(@user)
            render :show
        else
            render json: 'try again!'
        end

    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/bands/edit.html.erb
<h2> Edit a Band </h2>

<form action="<%= band_url(@band)%>" method = "POST">
<input type = "hidden" name = "_method" value = "PATCH">

<input type= "text" name = "band[name]" value = "<%=@band.name%>">

<button>Update Band</button>
</form>

MusicApp/app/views/bands/index.html.erb
<h2> All Bands </h1>

<div id ="band_list">
<% @bands.each do |band| %>
   <li> <%= band.name %> </li>
<% end %>
</div>

MusicApp/app/views/bands/show.html.erb
<h2> Band Name: <%= @band.name %> </h2>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <header>
    Music App
    <div class = "logic">
      <% if logged_in? %>
    <h2>Welcome <%= current_user.email %>!</h2>
    <form action="<%= session_url%>" method = "POST">
     <input type="hidden" name="authenticity_token"value="<%= form_authenticity_token %>">
      <input type="hidden" name = "_method" value = "DELETE">
      <button type = "submit" id= "header" > Sign Out </button>
    </form>
    <%end %>
    </div>
    </header>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<div class = 'page_headers'>
<h2>Sign up below for our music site</h2>
</div>

<form action=<%=users_url%> method= "POST">
 <input type="hidden" name="authenticity_token"value="<%= form_authenticity_token %>">

<label>Enter your email below:<br> 
    <input type ="text" name= "user[email]">
</label> <br><br>
<label>Enter your desired password below:<br>
    <input type ="text" name= "user[password]">
</label> <br>
<button type= "submit">Sign up here!</button>
<p>We are excited to have you!</p>
</form>

MusicApp/app/views/users/show.html.erb
<h2>Welcome <%= current_user.email %>! </h2>
<h2>Thanks for logging in!</h2>